### PR TITLE
Fix signed/unsigned comparison warning in Sockets.cpp

### PR DESCRIPTION
**Pull request by helmutw-copadata**
Fix warning '>': signed/unsigned mismatch in Sockets.cpp

### CODE REVIEW

**Comment by pbruenn** [comment]
Which compiler shows this warning to you? On which platform exactly?

**Comment by helmutw-copadata** [comment]
The platform is windows and the compiler Microsoft (R) C/C++ Optimizing Compiler Version 19.42.34433.
But I guess this L3 warning will be reported also with prior versions of the MS compiler.

**Comment by pbruenn** [comment]
Hmm, sorry it just feels wrong to cast to size_t unconditionally. gcc and clang are both smart enough to see that we compare a positive integer constant with a runtime value of size_t.
```
> cat bla.cpp 
#include <limits>
#include <iostream>

static size_t get_size() {
        return 10;
}

int main() {
        std::cerr << typeid(get_size()).name() << '\n';
        std::cerr << typeid(std::numeric_limits<int>::max()).name() << '\n';
        std::cerr << typeid(int).name() << '\n';
        std::cerr << typeid(-1).name() << '\n';
        if (get_size() > std::numeric_limits<int>::max()) {
                return 42;
        }
        if (get_size() > -1) {
                return 1;
        }
}
> g++ -Wall -pedantic bla.cpp -o bla && ./bla
bla.cpp: In function ‘int main()’:
bla.cpp:16:24: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
   16 |         if (get_size() > -1) {
      |             ~~~~~~~~~~~^~~~
m
i
i
i

```

Looking at this horrible cast for msvc https://github.com/Beckhoff/ADS/blob/6efd256c4b3ca2ac1830debee79cf692b627b750/AdsLib/Sockets.cpp#L164

And looking at all the other special cases already required for msvc:
https://github.com/Beckhoff/ADS/blob/6efd256c4b3ca2ac1830debee79cf692b627b750/.gitlab-ci.yml#L137

I am not yet ready to obfuscate the code even more for a in my opinion broken compiler. I will wait to address this problem until it will happen on our Windows reference platform. Maybe Microsoft will handle the warning similar to gcc and clang in the meantime. Until then I can only recommend to use another compiler or ignore this warning

**Comment by helmutw-copadata** [comment]
You are right that the compiler could detect that the constant expression is inside the valid range for size_t. Unfortunately MSVC does not and so does gcc when compiling C-code.

We are currently building only a subset of your files:

AdsLinuxLibrary\AdsDef.cpp"
AdsLinuxLibrary\AdsDevice.cpp
AdsLinuxLibrary\Frame.cpp"
AdsLinuxLibrary\Log.cpp"
AdsLinuxLibrary\Sockets.cpp"
AdsLinuxLibrary\standalone\AdsLib.cpp"
AdsLinuxLibrary\standalone\AmsConnection.cpp"
AdsLinuxLibrary\standalone\AmsNetId.cpp"
AdsLinuxLibrary\standalone\AmsPort.cpp"
AdsLinuxLibrary\standalone\AmsRouter.cpp"
AdsLinuxLibrary\standalone\NotificationDispatcher.cpp"

They all compile ok with W4 except of the warning mentioned above.

I updated the fix to be less obscuring.

**Comment by pbruenn** [comment]
How would you use std::numeric_limits in gcc in C mode?

**Comment by helmutw-copadata** [comment]
My point is just that gcc reports this warning in C code also when using constant values. For C++ it does not.
https://stackoverflow.com/questions/65776263/comparing-unsigned-vs-signed-does-not-make-a-warning-using-const

Its not very likely that the behaviour of the Microsoft compiler will be qualified as a bug. The compiler behaves as documented in 
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4018?view=msvc-170

**Comment by pbruenn** [comment]
Well, this is a C++ codebase so you can't win an argument with a C compiler. And the Microsoft link doesn't convince me either. 
You said you are using MSVC 19.42.34433. I can only test 19.40 on godbolt.org but I doubt that C4018 is emitted in your version. Instead I believe it is C4388. So warning level 4 and default off. Default off is therefore very much an indication that Microsoft is aware that this warning often overshoots the mark. This in turn is an indication for me that you are not compiling with /W4 but with /Wall. Basically, I'm with you all the way. I also use -Wall -pedantic whenever possible. But that only works with compilers that are developed by people with sensitivity and not by bureaucrats who just rattle off tokens.
Well, this is a C++ codebase so you can't win an argument with a C compiler. And the Microsoft link doesn't convince me either. 

You said you are using MSVC 19.42.34433. I can only test 19.40 on godbolt.org but I doubt that C4018 is emitted in your version. Instead I believe it is C4388. So warning level 4 and default off. Default off is therefore very much an indication that Microsoft is aware that this warning often overshoots the mark. This in turn is an indication for me that you are not compiling with /W4 but with /Wall. Basically, I'm with you all the way. I also use -Wall -pedantic whenever possible. But that only works with compilers that are developed by people with sensitivity and not by bureaucrats who just rattle off tokens.
Thanks for this discussion. I learned a lot and Iam still thinking about a solution to solve this puzzle in an elegant way.

**Comment by helmutw-copadata** [comment]
Well it is C4018.
If you do not believe me, simply try the following sample on godbolt.org with "x86 msvc v19.latest" with "/W3 /WX"

```
#include <vector>
#include <limits>

int main()
{
  std::vector<int> x;
  if (x.size() > (std::numeric_limits<int>::max)())
  {
    return 1;
  }
  return 0;
}
```
it results with:

<source>(8): error C2220: the following warning is treated as an error
<source>(8): warning C4018: '>': signed/unsigned mismatch

You are welcome. I will close the PR. Disabling warnings globally or for a whole file always comes with a bad feeling.
I therefore prefer to either fix them or supress them individually. That is why I created the PR.

**Comment by pbruenn** [comment]
Well, that's why I asked "What platform **exactly**?". Of course x86 is different than x64.

**Pull request closed without merging**
